FROM python:3.14-bookworm

WORKDIR /app

COPY requirements-naive.txt .

RUN pip install --no-cache-dir -r requirements-naive.txt

COPY generate_dataset.py .
COPY train.py .
COPY app.py .

RUN python generate_dataset.py
RUN python train.py --data spam_dataset.csv --out model.joblib

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]