FROM python:3.10 AS builder

WORKDIR /build

RUN pip install --no-cache-dir \
    --target=/build/deps \
    kubernetes

FROM python:3.10-slim

WORKDIR /app

COPY --from=builder \
    /build/deps \
    /usr/local/lib/python3.10/site-packages

COPY validate_shard.py .

COPY shards ./shards

CMD ["python", "validate_shard.py"]